# This is a basic workflow to help you get started with Actions

name: My_git_Hub_Basics
env:
  APPLICATION_NAME: "My_flask"
  PACAGE_NAME : "flask-deploy-ver-${{ github.sha }}
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  My_testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: #Таски
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Helllo, world!
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "Appication name: ${{ env.APPLICATION_NAME }}"
  My_test_name:
    runs-on: ubuntu-latest
    needs: [My_testing] #Команда для последовательного запуска
    steps:
      - name: Print Hello Message
        run: echo Hello, worldkkkk!
      - name : Execure few commands
        run : |
          echo "Hello Mesage1"
          echo "Hello Mesage2"
          echo "Deploy name: ${{ env.PACAGE_NAME }}"
